version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y4f5a6u0
  build:
    commands:
      - docker build -t my-repos:latest .
      - docker tag my-repos:latest public.ecr.aws/y4f5a6u0/my-repos:latest
  post_build:
    commands:
      - docker push public.ecr.aws/y4f5a6u0/my-repos:latest
      - printf '[{"name":"myrepos","imageUri":"%s"}]' public.ecr.aws/y4f5a6u0/my-repos:latest > imagedefinitions.jso
artifacts:
  files: imagedefinitions.json
